// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR35tsxpPoYODt5Ms_xRPFL8B8Cq4ihOI',
    appId: '1:259612726986:web:508c7ebff8599257b4c633',
    messagingSenderId: '259612726986',
    projectId: 'social-connect-v1',
    authDomain: 'social-connect-v1.firebaseapp.com',
    storageBucket: 'social-connect-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS8XSEQM73mL9I-2XtBs2_0gGxqeoFfz4',
    appId: '1:259612726986:android:89e7dcb9d83a6419b4c633',
    messagingSenderId: '259612726986',
    projectId: 'social-connect-v1',
    storageBucket: 'social-connect-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBAsFp3Gp35c0t-pToGB1bERN_5qbVf4',
    appId: '1:259612726986:ios:d2635d0243964c3eb4c633',
    messagingSenderId: '259612726986',
    projectId: 'social-connect-v1',
    storageBucket: 'social-connect-v1.firebasestorage.app',
    iosBundleId: 'com.example.socialConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBAsFp3Gp35c0t-pToGB1bERN_5qbVf4',
    appId: '1:259612726986:ios:d2635d0243964c3eb4c633',
    messagingSenderId: '259612726986',
    projectId: 'social-connect-v1',
    storageBucket: 'social-connect-v1.firebasestorage.app',
    iosBundleId: 'com.example.socialConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR35tsxpPoYODt5Ms_xRPFL8B8Cq4ihOI',
    appId: '1:259612726986:web:8d7230d842d0b512b4c633',
    messagingSenderId: '259612726986',
    projectId: 'social-connect-v1',
    authDomain: 'social-connect-v1.firebaseapp.com',
    storageBucket: 'social-connect-v1.firebasestorage.app',
  );
}
